<?php

namespace Tms\RunnerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RunnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RunnerRepository extends EntityRepository
{
}
