<?php

namespace Wlm\OperationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationBucketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class _OperationsRepository extends EntityRepository
{
}
