<?php

namespace Wlm\OperationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRepository extends EntityRepository
{
	
}
