<?php

namespace Wlm\ClientBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Wlm\ClientBundle\Entity\Client;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function  getSearchList ($formvalue) 
	{
 

		$query = $this->_em->createQuery("SELECT c FROM WlmClientBundle:Client c  WHERE c.lastName LIKE :foo OR c.firstName LIKE :foo" );
		$query->setParameter('foo', '%'.$formvalue.'%');
		$result = $query->getResult();

		return $result;

	}
}
