parameters:
#    wlm_client.example.class: Wlm\ClientBundle\Example

services:
#    wlm_client.example:
#        class: %wlm_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
