parameters:
#    ghw_client.example.class: Ghw\ClientBundle\Example

services:
#    ghw_client.example:
#        class: %ghw_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
