<?php

namespace Tms\RaceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tms\RaceBundle\Entity\Arrivals;


/**
 * ArrivalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivalsRepository extends EntityRepository
{
	 public function findAllOrderedByArrivalTime()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TmsRaceBundle:Arrivals a ORDER BY a.timeStop ASC')
            ->getResult();
    }
	 public function findLatestArrivalTime()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM TmsRaceBundle:Arrivals a WHERE a.timeStop=(SELECT MIN(b.timeStop) FROM TmsRaceBundle:Arrivals b WHERE b.code is NULL)  
  ')
            ->getSingleResult();
    }
}


