parameters:
#    tms_runner.example.class: Tms\RunnerBundle\Example

services:
#    tms_runner.example:
#        class: %tms_runner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
