parameters:
#    wlm_scanner.example.class: Wlm\Bundle\ScannerBundle\Example

services:
#    wlm_scanner.example:
#        class: %wlm_scanner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
