parameters:
#    ghw_main.example.class: Ghw\MainBundle\Example

services:
#    ghw_main.example:
#        class: %ghw_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
