<?php

namespace Wlm\TillBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TillRepository extends EntityRepository
{

}
