parameters:
#    wlm_location.example.class: Wlm\LocationBundle\Example

services:
#    wlm_location.example:
#        class: %wlm_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    wlm.validator.antiflood:                             # Le nom du service
        class: Wlm\OperationBundle\Validator\AntiFloodValidator   # La classe du service, ici notre validateur déjà créé
        arguments: [@request, @doctrine.orm.entity_manager]  # Les données qu'on injecte au service : la requête et l'EntityManager
        scope: request                                       # Comme on injecte la requête, on doit préciser ce scope
        tags:
            - { name: validator.constraint_validator, alias: wlm_antiflood }  # C'est avec l'alias qu'on retrouvera le service