<?php

namespace Wlm\EquipmentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterRepository extends EntityRepository
{
}
